### ISSUE TITLE
Kebechet does not recognize me as a mainainer

### ISSUE THREAD

**Issue by CermakM** [thoth-station/kebechet#226]
**Describe the bug**
Kebechet does not recognize me as a maintainer when I create and issue for minor release, despite stating me in maintainers list (see the attached issue):

`Sorry, @CermakM but you are not stated in maintainers section for this project. Maintainers are @CermakM`

My config:
```
---
repositories:
  - slug: CermakM/jupyter-datatables
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: info
      - name: update
        configuration:
          labels: [bot]
      - name: version
        configuration:
          maintainers:
            - cermakm
          assignees:
            - cermakm
          changelog_file: true

  - slug: CermakM/jupyter-require
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: info
      - name: update
        configuration:
          labels: [bot]
      - name: version
        configuration:
          maintainers:
            - cermakm
          assignees:
            - cermakm
changelog_file: true
```

**Expected behavior**
I am recognized as a maintainer and I can issue minor release successfully.

**Additional context**
https://github.com/CermakM/jupyter-datatables/issues/12
