### ISSUE TITLE
Extend Kebechet managers with "enabled" flag

### ISSUE THREAD

**Issue by fridex** [thoth-station/kebechet#849]
**Is your feature request related to a problem? Please describe.**

As discussed on the Tech talk:

I, as a user, would like to disable a manager but preserve entry in the `managers` section in `.thoth.yaml` file. To support this, we could add a new entry, such as "enabled", to the Kebechet manager entry.

**Describe the solution you'd like**

```yaml
managers:
  - name: version
    enabled: true # <<<<
    configuration: {}
```

**Describe alternatives you've considered**

Delete entries from `.thoth.yaml`, but that also loses information about available managers that can be eventually re-enabled.

References: https://docs.google.com/document/d/1XmXYEWEwgOBHqdJkUTmhBvUb41pr5GIR2pePasvvZ1s/edit#
